name: Laravel Migrate and Seed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  migrate-seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: |
          composer install
          cp .env.example .env
          php artisan key:generate

      - name: Inject Database URL
        run: |
          echo "DATABASE_URL=mysql://if0_38063719:Ade5oyin@sql203.infinityfree.com:3306/if0_38063719_themes" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Seed Database
        run: php artisan db:seed --class=DatabaseSeeder
